name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:

    # 1. Checkout code
    - name: Checkout Repository
      uses: actions/checkout@v3

    # 2. Configure AWS credentials (for ECR access)
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    # 3. Login to Amazon ECR
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    # 4. Build Docker image
    - name: Build Docker Image
      run: docker build -t devops-app .

    # 5. Tag Docker image
    - name: Tag Docker Image
      run: docker tag devops-app:latest 816975732391.dkr.ecr.ap-south-1.amazonaws.com/devops-app:latest

    # 6. Push image to ECR
    - name: Push to ECR
      run: docker push 816975732391.dkr.ecr.ap-south-1.amazonaws.com/devops-app:latest

    # 7. Deploy to EC2
    - name: Deploy on EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          echo "Stopping old container..."
          sudo docker stop devops-app || true
          sudo docker rm devops-app || true

          echo "Logging into ECR..."
          aws ecr get-login-password --region ap-south-1 \
          | sudo docker login --username AWS --password-stdin 816975732391.dkr.ecr.ap-south-1.amazonaws.com

          echo "Pulling latest image..."
          sudo docker pull 816975732391.dkr.ecr.ap-south-1.amazonaws.com/devops-app:latest

          echo "Running container..."
          sudo docker run -d -p 8080:8080 --name devops-app \
          816975732391.dkr.ecr.ap-south-1.amazonaws.com/devops-app:latest

          echo "Deployment successful!"